"""Covenant report value objects."""

from dataclasses import dataclass
from decimal import Decimal


@dataclass(frozen=True)
class ExcludedAsset:
    """Represents an excluded asset with reason."""

    asset_id: str
    reason: str


@dataclass(frozen=True)
class CovenantReport:
    """Deterministic covenant report generated by the use case."""

    facility_id: str
    as_of_date: str
    effective_rate: Decimal
    covenant_status: str
    total_assets_evaluated: int
    included_asset_ids: list[str]
    excluded_assets_with_reasons: list[ExcludedAsset]
    report_hash: str
